<a href="https://colab.research.google.com/github/JJAYAKUMAR21/numpy-task100/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
x = np.zeros((10,10))
print("%d bytes" % (x.size * x.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [9]:
y = np.arange(50)
y = y[::-1]
print(y)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [10]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [12]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [13]:
x = np.random.random((3,3,3))
print(x)

[[[0.08136813 0.55567766 0.8762153 ]
  [0.32589284 0.45581546 0.61619025]
  [0.43713037 0.72158066 0.88964589]]

 [[0.9291214  0.21944925 0.81322278]
  [0.42852602 0.98915016 0.89018168]
  [0.91864597 0.90969996 0.7210831 ]]

 [[0.53459229 0.90187774 0.20719058]
  [0.14943278 0.55037644 0.86777329]
  [0.21569846 0.27235413 0.42280213]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [14]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

0.0004171671218771156 0.9910483179370746


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [15]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4762401755188366


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [16]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [17]:
y = np.ones((5,5))
y = np.pad(y, pad_width=1, mode='constant', constant_values=0)
print(y)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [22]:
array = np.ones(64,dtype=int)
array[::2]=0
array = array.reshape((8,8))
print(array)


[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [23]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [24]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [25]:
y = np.random.random((5,5))
y = (y - np.mean (y)) / (np.std (y))
print(y)

[[ 0.17473861  1.45264374  0.42663683  1.82753845  0.50272217]
 [ 0.89915831 -0.24218838 -0.23017335  0.92081304 -1.23619226]
 [ 1.39104962 -1.28339034  1.59004067 -1.03193832  0.1768319 ]
 [-0.11914758 -0.4114933  -1.30204085 -0.97557935 -1.62130692]
 [-0.05148302  0.71777828 -1.58188923 -0.22292199  0.22979325]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [28]:
color = np.dtype([("R", np.ubyte),
                  ("G", np.ubyte),
                  ("B", np.ubyte),
                  ("A", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [29]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [30]:
X = np.arange(11)
X[(3 < X) & (X < 8)] *= -1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
all


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [34]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-34-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-34-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [35]:
i = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(i)), i))

[ 4.  2. -7.  9. -3.  1.  9. -3. -4. -1.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [36]:
X = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print(np.intersect1d(X,y))

[0 1 2 3 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [41]:
np.seterr(all="ignore")


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [42]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [44]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [45]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [46]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [47]:
a = np.random.uniform(0,10,10)

print(a - a%1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[8. 0. 1. 9. 0. 3. 5. 8. 2. 7.]
[8. 0. 1. 9. 0. 3. 5. 8. 2. 7.]
[8. 0. 1. 9. 0. 3. 5. 8. 2. 7.]
[8 0 1 9 0 3 5 8 2 7]
[8. 0. 1. 9. 0. 3. 5. 8. 2. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [48]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [49]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [50]:
y = np.linspace(0,1,11,endpoint=False)[1:]
print(y)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [51]:
a = np.random.random(10)
a.sort()
print(a)

[0.07026699 0.15109126 0.16919358 0.25813857 0.35035459 0.38270664
 0.61707473 0.6358383  0.6480781  0.71650769]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [52]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [54]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)


equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [57]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [58]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.28486643 0.75358297 0.86663159 0.49552139 0.67408343 0.95505492
 0.78552999 0.57361901 1.11841917 0.87459537]
[1.21847302 0.59008825 0.86282345 1.09747402 0.88490556 0.69920132
 0.64944352 0.40186775 0.88794427 0.59795252]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [60]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.55571286 0.15623891 0.60624433 0.19388642 0.82321854 0.53417219
 0.         0.0755073  0.27233596 0.07275052]
[0.53994362 0.67907252 0.79375349 0.35215039 0.         0.3256059
 0.65523709 0.90108223 0.42504779 0.49540239]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [62]:
a = np.zeros((4,4), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,4),
                             np.linspace(0,1,4))
print(a)

[[(0.        , 0.        ) (0.33333333, 0.        )
  (0.66666667, 0.        ) (1.        , 0.        )]
 [(0.        , 0.33333333) (0.33333333, 0.33333333)
  (0.66666667, 0.33333333) (1.        , 0.33333333)]
 [(0.        , 0.66666667) (0.33333333, 0.66666667)
  (0.66666667, 0.66666667) (1.        , 0.66666667)]
 [(0.        , 1.        ) (0.33333333, 1.        )
  (0.66666667, 1.        ) (1.        , 1.        )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [64]:
X = np.arange(6)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

396.0368295558234


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [65]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [67]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((10,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [69]:
Z = np.arange(50)
v = np.random.uniform(0,50)
index = (np.abs(Z-v)).argmin()
print(Z[index])

21


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [3]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-3-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [4]:
a = np.random.random((10,2))
X,Y = np.atleast_2d(a[:,0], a[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.65533896 0.38897334 0.51588066 0.31548788 0.43042996
  0.61364209 0.42525158 0.50005883 0.6008921 ]
 [0.65533896 0.         0.93203271 0.38641802 0.7048836  0.56168466
  0.74652246 0.29019203 0.16360217 0.74515046]
 [0.38897334 0.93203271 0.         0.89203061 0.24427731 0.81923155
  0.99291772 0.77372441 0.80562128 0.97949172]
 [0.51588066 0.38641802 0.89203061 0.         0.732434   0.19806834
  0.36013049 0.16428476 0.27148522 0.35903108]
 [0.31548788 0.7048836  0.24427731 0.732434   0.         0.70932523
  0.91317066 0.59078764 0.59451202 0.90140864]
 [0.43042996 0.56168466 0.81923155 0.19806834 0.70932523 0.
  0.2220462  0.28342945 0.41845414 0.21419645]
 [0.61364209 0.74652246 0.99291772 0.36013049 0.91317066 0.2220462
  0.         0.49106153 0.62058271 0.01440027]
 [0.42525158 0.29019203 0.77372441 0.16428476 0.59078764 0.28342945
  0.49106153 0.         0.13585545 0.48654631]
 [0.50005883 0.16360217 0.80562128 0.27148522 0.59451202 0.41845414
  0.62058271 0.135855

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [5]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[29 15 13 86 67 25 38 14 73 32]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [20]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-20-b46e6554b0bd>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [21]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [25]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
A = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (A-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [26]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [27]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.372547   -0.11713806 -0.19960557  0.52569789  0.18923261 -0.39416263
   0.30720292 -0.26361594 -0.21097797 -0.20918027]
 [-0.15813393  0.24309324  0.04242653 -0.10084709  0.0875014   0.01208296
   0.09148531 -0.08140996 -0.28850228  0.15230381]
 [ 0.2704759  -0.21019095  0.12671314 -0.25216175 -0.24096225  0.13363152
   0.67802067 -0.21630986 -0.19463074 -0.09458568]
 [ 0.30359643 -0.16404369  0.37859628 -0.47572819  0.20266568 -0.24267925
   0.35125785  0.00324674  0.12267518 -0.47958701]
 [-0.40045864  0.05477456  0.1534309  -0.38115339 -0.24340592  0.27729411
   0.15658688  0.22355984  0.41195098 -0.25257931]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [28]:
A = np.random.randint(0,10,(3,3))
print(A)
print(A[A[:,1].argsort()])

[[8 6 4]
 [9 4 2]
 [7 5 5]]
[[9 4 2]
 [7 5 5]
 [8 6 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [29]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [30]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5691689061031364


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [31]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [32]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [33]:
a = np.ones(10)
I = np.random.randint(0,len(a),20)
a += np.bincount(I, minlength=len(a))
print(a)

[3. 1. 2. 1. 4. 3. 3. 4. 4. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [34]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [35]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [36]:
A = np.random.randint(0,10,(3,4,3,4))
# by passing a tuple of axes 
sum = A.sum(axis=(-2,-1))
print(sum)

[[61 46 48 52]
 [51 50 61 48]
 [63 58 57 65]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [37]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.59310143 0.53085928 0.39917838 0.48606659 0.58850829 0.44159128
 0.48539852 0.47678768 0.56585732 0.45066276]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [38]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.41897036, 1.96456909, 0.72558545, 1.49934195, 1.2247124 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [39]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [40]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [41]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [42]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 5, 17) ( 5, 58) ( 8, 18) ( 8, 35) (12, 16) (12, 48) (16, 34) (16, 42)
 (16, 48) (17, 58) (18, 35) (29, 37) (29, 43) (29, 61) (29, 92) (30, 50)
 (30, 72) (34, 42) (37, 43) (38, 46) (38, 99) (46, 57) (46, 60) (46, 99)
 (50, 72) (51, 65) (51, 96) (57, 60) (61, 92) (65, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [43]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [48]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [50]:
from numpy.lib import stride_tricks
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [51]:
A = np.random.randint(0,2,100)
np.logical_not(A, out=A)

A = np.random.uniform(-1.0,1.0,100)
np.negative(A, out=A)

array([ 0.20197723, -0.26214432, -0.02235244, -0.8353604 ,  0.39346688,
       -0.15514443,  0.98348873, -0.23853579, -0.78237697, -0.35045062,
        0.64128027, -0.03083661, -0.79752513, -0.28758962, -0.55074732,
       -0.840038  , -0.82566848, -0.72525725, -0.98805608, -0.29954976,
       -0.49578869,  0.69455086, -0.02413191, -0.64548815,  0.74178741,
        0.18693094,  0.49737099, -0.14883881,  0.66773387,  0.54570368,
       -0.74352668,  0.33089712, -0.97769359,  0.89062475,  0.72832728,
        0.67939296,  0.95808965, -0.65149816,  0.22389734, -0.69744013,
       -0.0737927 , -0.61126681,  0.69003247,  0.33442646, -0.95010604,
        0.60653338,  0.77901174,  0.0532744 ,  0.22163809,  0.42651376,
       -0.7018355 , -0.99460298, -0.03687981,  0.79474686,  0.43807998,
       -0.06968372, -0.39187851,  0.31933323,  0.57045992,  0.8575262 ,
       -0.01555956, -0.31700348,  0.77845905,  0.70369986, -0.86738121,
       -0.14168092,  0.17436595,  0.11250063,  0.97205587,  0.43

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [52]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[7.11248248 1.00238482 5.01077854 2.95403049 2.70676501 5.47051039
 5.25251835 0.13252891 9.62184548 2.93000922]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [53]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.92490633 13.5027449   1.30198166  4.45975014 13.63361775  9.44944215
   4.28244162 13.11603956  7.15783887  0.34034389]
 [ 8.82084669 17.00823582  0.2206751   3.03326809 13.1516196  12.7985134
   2.10912847 16.15563806 10.58860874  3.70907491]
 [ 8.00921513  0.58716134 13.8138376   1.42621621  4.78981503  4.84213752
   1.20136305  1.35730685  7.03991024 11.98149506]
 [ 9.68205793 17.26529713  1.86587033  0.4747596  10.83943182 12.86873754
   0.5457312  15.90208741 10.75398912  4.98487936]
 [ 0.94305241  5.61435662 12.42200573  4.69128938  3.24911884  1.0296694
   3.39748515  3.87603749  0.99662807  4.52193777]
 [ 0.48902621  8.67517008  2.64531897  6.63166665 14.48987361  4.85210485
   7.48636946  8.97034358  2.44045297  5.99973513]
 [ 1.44529289  5.70361038 19.25371142 14.48812777  5.81940432  0.41741078
  13.37874614  2.05833577  1.25214766  0.52538643]
 [ 7.53572692 14.91434567  3.98879701  0.55753554  9.31723326 10.48054859
   1.11087146 13.4774107   8.38328023  3.06253635]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [55]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [59]:
A = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(A)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [60]:
A = np.random.randint(0,10,50)
print(np.bincount(A).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [63]:
from numpy.lib import stride_tricks
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 1 1]
   [2 1 0]
   [4 3 4]]

  [[1 1 0]
   [1 0 2]
   [3 4 4]]

  [[1 0 4]
   [0 2 3]
   [4 4 4]]

  [[0 4 0]
   [2 3 1]
   [4 4 1]]

  [[4 0 3]
   [3 1 3]
   [4 1 2]]

  [[0 3 0]
   [1 3 4]
   [1 2 2]]

  [[3 0 3]
   [3 4 2]
   [2 2 1]]

  [[0 3 3]
   [4 2 4]
   [2 1 4]]]


 [[[2 1 0]
   [4 3 4]
   [3 0 1]]

  [[1 0 2]
   [3 4 4]
   [0 1 2]]

  [[0 2 3]
   [4 4 4]
   [1 2 3]]

  [[2 3 1]
   [4 4 1]
   [2 3 3]]

  [[3 1 3]
   [4 1 2]
   [3 3 3]]

  [[1 3 4]
   [1 2 2]
   [3 3 0]]

  [[3 4 2]
   [2 2 1]
   [3 0 0]]

  [[4 2 4]
   [2 1 4]
   [0 0 1]]]


 [[[4 3 4]
   [3 0 1]
   [3 1 2]]

  [[3 4 4]
   [0 1 2]
   [1 2 0]]

  [[4 4 4]
   [1 2 3]
   [2 0 4]]

  [[4 4 1]
   [2 3 3]
   [0 4 4]]

  [[4 1 2]
   [3 3 3]
   [4 4 0]]

  [[1 2 2]
   [3 3 0]
   [4 0 3]]

  [[2 2 1]
   [3 0 0]
   [0 3 2]]

  [[2 1 4]
   [0 0 1]
   [3 2 0]]]


 [[[3 0 1]
   [3 1 2]
   [4 3 4]]

  [[0 1 2]
   [1 2 0]
   [3 4 4]]

  [[1 2 3]
   [2 0 4]
   [4 4 1]]

  [[2 3 3]
   [0 4 4]
   [4 1 0]]

  [[3 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [64]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        a,b = index
        super(Symetric, self).__setitem__((a,b), value)
        super(Symetric, self).__setitem__((b,a), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  5 10 12  8]
 [ 5  8  9  7  9]
 [10  9  0 42  8]
 [12  7 42  7  5]
 [ 8  9  8  5  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [65]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [66]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [69]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[95 96 97 98 99]
[97 99 98 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [70]:
A = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(A.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [74]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [75]:
A = np.random.randint(0,5,(10,3))
print(A)
# arrays of all dtypes 
E = np.all(A[:,1:] == A[:,:-1], axis=1)
U = A[~E]
print(U)
#  for numerical arrays 
U = A[A.max(axis=1) != A.min(axis=1),:]
print(U)

[[2 0 0]
 [3 0 2]
 [2 0 4]
 [0 3 2]
 [4 4 3]
 [3 4 1]
 [2 0 1]
 [4 2 0]
 [1 2 0]
 [4 3 3]]
[[2 0 0]
 [3 0 2]
 [2 0 4]
 [0 3 2]
 [4 4 3]
 [3 4 1]
 [2 0 1]
 [4 2 0]
 [1 2 0]
 [4 3 3]]
[[2 0 0]
 [3 0 2]
 [2 0 4]
 [0 3 2]
 [4 4 3]
 [3 4 1]
 [2 0 1]
 [4 2 0]
 [1 2 0]
 [4 3 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [76]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(A[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [78]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
result = Z[idx]
print(result)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [79]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.29872041, 0.22314767, 0.28639187, 0.29013425, 0.18407225,
        0.01883523, 0.25575121, 0.12121438, 0.03897091, 0.06220544],
       [0.15448167, 0.11539963, 0.14810603, 0.15004138, 0.09519198,
        0.00974054, 0.13226038, 0.06268537, 0.0201536 , 0.03216921],
       [0.56550134, 0.42243616, 0.54216242, 0.54924705, 0.34846331,
        0.03565657, 0.48415725, 0.22946839, 0.07377501, 0.11775982],
       [0.15365234, 0.11478011, 0.14731093, 0.14923589, 0.09468095,
        0.00968825, 0.13155034, 0.06234885, 0.0200454 , 0.03199652],
       [0.23084963, 0.17244739, 0.22132219, 0.22421428, 0.14225011,
        0.01455577, 0.19764325, 0.09367386, 0.03011652, 0.04807205],
       [0.28026619, 0.20936215, 0.26869927, 0.27221046, 0.17270071,
        0.01767163, 0.23995152, 0.11372605, 0.03656338, 0.05836254],
       [0.21235232, 0.15862968, 0.20358828, 0.20624864, 0.13085202,
        0.01338946, 0.18180667, 0.08616804, 0.02770337, 0.04422018],
       [0.62812817, 0.46921914, 0.6022045

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [82]:
x = 3.6
xp = [2, 4, 6]
fp = [1, 3, 5]
   
gfg = np.interp(x, xp, fp)
  
print (gfg)

2.6


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [80]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [81]:
X = np.random.randn(100) 
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30434911  0.04556585]
